"""HealthMes-owned contracts and orchestration for wellness decisions.

The contract module is intentionally imported eagerly, while heavier
orchestration modules are exposed lazily.  Low-level modules such as
``healthmes.wearables.search`` import the contracts package and must not
initialize every decision provider as a side effect.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

from healthmes.decision.contracts import (
    CompatibilityPreset,
    ContextCoverage,
    ContextFreshness,
    ContextQuery,
    ContextResult,
    ContextStatus,
    CoverageStatus,
    DecisionAction,
    DecisionActionKind,
    DecisionActionState,
    DecisionBudget,
    DecisionCaller,
    DecisionContextHints,
    DecisionDraft,
    DecisionPersistenceIntent,
    DecisionRecordSummaryCode,
    DecisionRequest,
    DecisionResult,
    DecisionStatus,
    ExecutionScope,
    FreshnessStatus,
    PersistenceStatus,
    PrivacyLevel,
    RawSourceHandle,
    RuntimeMetadata,
    SourceRef,
    ToolCallRecord,
    ToolCallStatus,
    decision_record_summary,
    source_ref_id,
)

_LAZY_MODULES = (
    "healthmes.decision.access",
    "healthmes.decision.agent",
    "healthmes.decision.compatibility",
    "healthmes.decision.composition",
    "healthmes.decision.domain_providers",
    "healthmes.decision.engine",
    "healthmes.decision.execution",
    "healthmes.decision.finalizer",
    "healthmes.decision.hermes_profile",
    "healthmes.decision.policy",
    "healthmes.decision.providers",
    "healthmes.decision.responses",
    "healthmes.decision.runtime",
    "healthmes.decision.search",
    "healthmes.decision.service",
)

__all__ = [
    "AccessAuditEntry",
    "AccessOutcome",
    "AbortedDecisionSearchSessionError",
    "ActivityContextProvider",
    "BusyDecisionSearchSessionError",
    "CalendarContextProvider",
    "CompatibilityPreset",
    "ContextCapability",
    "ContextAccessLayer",
    "ContextAccessPolicy",
    "ContextAccessTurn",
    "ContextCoverage",
    "ContextFreshness",
    "ContextParameterFormat",
    "ContextParameterSpec",
    "ContextParameterType",
    "ContextProvider",
    "ContextProviderDescriptor",
    "ContextProviderMetadata",
    "ContextProviderRegistry",
    "ContextProviderRegistryError",
    "ContextQuery",
    "ContextResult",
    "ContextSearchAccessAudit",
    "ContextSearchResult",
    "ContextStatus",
    "ContextToolCall",
    "CoverageStatus",
    "DatabaseDecisionPolicyResolver",
    "DecisionAgentRun",
    "DecisionAction",
    "DecisionActionKind",
    "DecisionActionState",
    "DecisionBudget",
    "DecisionCaller",
    "DecisionChannelAdapter",
    "DecisionChannelRequest",
    "DecisionContextHints",
    "DecisionContextSearchSessionService",
    "DecisionDraft",
    "DecisionEngineBusyError",
    "DecisionEngineClosedError",
    "DecisionExecutionControl",
    "DecisionFinalizer",
    "DecisionIdempotencyConflictError",
    "DecisionIdempotencyExpiredError",
    "DecisionIdempotencyUnavailableError",
    "DecisionIngress",
    "DecisionPersistenceIntent",
    "DecisionRecordSummaryCode",
    "DecisionRecoveryNotFoundError",
    "DecisionResult",
    "DecisionRequest",
    "DecisionRuntime",
    "DecisionRuntimeContractError",
    "DecisionRuntimeError",
    "DecisionRuntimeNotConfiguredError",
    "DecisionRuntimeTurn",
    "DecisionRuntimeUnavailableError",
    "DecisionSearchBudgetError",
    "DecisionSearchBudgetUsage",
    "DecisionSearchPolicyError",
    "DecisionSearchQueryError",
    "DecisionSearchRelatedRecord",
    "DecisionSearchSessionCapacityError",
    "DecisionSearchSessionError",
    "DecisionSearchSessionHandle",
    "DecisionSearchSessionSnapshot",
    "DecisionSearchSessionState",
    "DecisionServiceRequest",
    "DecisionStatus",
    "DecisionToolCallError",
    "DecisionToolSpec",
    "DECISION_DOMAINS",
    "DECISION_PAYLOAD_SCHEMA",
    "DECISION_RECORD_SCHEMA",
    "DisabledProviderError",
    "DomainAccessGrant",
    "DuplicateCapabilityError",
    "DuplicateProviderError",
    "ExecutionScope",
    "ExpiredDecisionSearchSessionError",
    "FinishedDecisionSearchSessionError",
    "FreshnessStatus",
    "HERMES_DECISION_DRAFT_SCHEMA",
    "HERMES_DECISION_MCP_SERVER",
    "HERMES_DECISION_MCP_TOOL_NAMES",
    "HERMES_DECISION_NATIVE_TOOLSET_DENYLIST",
    "HERMES_DECISION_SKILL_MCP_TOOL_NAMES",
    "HERMES_DECISION_TOOL_ALLOWLIST",
    "HERMES_RESPONSES_PATH",
    "HERMES_RESPONSES_POLICY_VERSION",
    "HERMES_TOOLSETS_PATH",
    "HealthMesDecisionEngine",
    "HealthMesDecisionService",
    "decision_rest_request_id",
    "HermesDecisionProfileAssertion",
    "HermesDecisionProfileError",
    "HermesHttpResponsesTransport",
    "HermesResponsesContractError",
    "HermesResponsesDecisionAgent",
    "HermesResponsesError",
    "HermesResponsesHttpResult",
    "HermesResponsesTransport",
    "HermesResponsesTransportError",
    "HermesRuntimeAttestationAssertion",
    "NutritionContextProvider",
    "PersistenceStatus",
    "PrivacyLevel",
    "ProvenanceSupport",
    "RawSourceHandle",
    "RuntimeContextResult",
    "RuntimeDecisionContextHints",
    "RuntimeDecisionRequest",
    "RuntimeMetadata",
    "RuntimeRelatedRecord",
    "RuntimeResourceBudget",
    "RuntimeStepOutput",
    "RuntimeToolExchange",
    "SourceRef",
    "ToolCallRecord",
    "ToolCallStatus",
    "UnknownCapabilityError",
    "UnknownDecisionSearchSessionError",
    "UnknownProviderError",
    "WearableContextProvider",
    "build_configured_decision_engine",
    "build_context_provider_registry",
    "build_decision_context_search_session_service",
    "build_decision_recovery_finalizer",
    "build_healthmes_responses_decision_engine",
    "decision_access_policy",
    "decision_record_summary",
    "decision_request_fingerprint",
    "decision_request_from_activity_context",
    "decision_request_timezone_from_record",
    "decision_result_from_record",
    "ensure_decision_domain_policies",
    "list_decision_domain_policies",
    "local_owner_access_policy",
    "resolve_decision_execution_scope",
    "source_ref_id",
    "update_decision_domain_policy",
    "validate_context_parameters",
]


def __getattr__(name: str) -> Any:
    """Resolve a public orchestration symbol on first use."""

    if name not in __all__:
        raise AttributeError(
            f"module {__name__!r} has no attribute {name!r}"
        )
    for module_name in _LAZY_MODULES:
        module = import_module(module_name)
        if hasattr(module, name):
            value = getattr(module, name)
            globals()[name] = value
            return value
    raise AttributeError(
        f"module {__name__!r} has no attribute {name!r}"
    )


def __dir__() -> list[str]:
    """Include lazy exports in introspection and IDE completion."""

    return sorted(set(globals()) | set(__all__))
