"""Photo-derived intake observations and storage adapters."""

from healthmes.nutrition.contracts import (
    CaffeineConfirmation,
    Confidence,
    ConfirmationStatus,
    Estimate,
    EstimateKind,
    IntakeItem,
    IntakeType,
    MetadataSource,
    NutrientEstimate,
    NutritionObservation,
    NutritionReview,
    ObservationStatus,
    ReviewedNutritionItem,
    VisionProvenance,
    observation_from_payload,
    observation_to_payload,
)
from healthmes.nutrition.intake_contracts import (
    CaptureModality,
    DecisionScope,
    DecisionStatus,
    EvidenceOrigin,
    IntakeDecision,
    IntakeDecisionRequest,
    IntakeIntent,
    IntakeInteraction,
    IntakeOutcome,
    IntakeOutcomeStatus,
    NormalizedIntakeItem,
    NutrientFact,
    StructuredIntakeSnapshot,
)

__all__ = [
    "CaffeineConfirmation",
    "Confidence",
    "ConfirmationStatus",
    "Estimate",
    "EstimateKind",
    "IntakeItem",
    "IntakeType",
    "MetadataSource",
    "NutrientEstimate",
    "NutritionReview",
    "NutritionObservation",
    "ObservationStatus",
    "ReviewedNutritionItem",
    "VisionProvenance",
    "CaptureModality",
    "DecisionScope",
    "DecisionStatus",
    "EvidenceOrigin",
    "IntakeDecision",
    "IntakeDecisionRequest",
    "IntakeIntent",
    "IntakeInteraction",
    "IntakeOutcome",
    "IntakeOutcomeStatus",
    "NormalizedIntakeItem",
    "NutrientFact",
    "StructuredIntakeSnapshot",
    "observation_from_payload",
    "observation_to_payload",
]
